<?php

/**
 * Generated by SymfonyId Admin Bundle
 * Url: https://github.com/symfonyid/SymfonyIdAdminBundle
 */

namespace AppBundle\Admin;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use SymfonyId\AdminBundle\Annotation as Siab;
use SymfonyId\AdminBundle\Controller\CrudController;

/**
 * @Route("/idname")
 *
 * @Siab\Page("IdName", description="Description of IdName")
 * @Siab\Crud("AppBundle\Entity\IdName", form="AppBundle\Form\IdNameType")
 * @Siab\Grid(@Siab\Column({"name"}), filter=@Siab\Filter({"name"}))
 */
class IdNameController extends CrudController
{
    public function getClassName()
    {
        return __CLASS__;
    }
}
